### ISSUE TITLE
Could not resolve host: virtualization.modern.ie

### ISSUE THREAD

**Issue by chrisspen** [xdissent/ievms#323]
The quickstart command does not work and fails with the error:

    curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | bash
    Checking for VirtualBox
    Checking for Oracle VM VirtualBox Extension Pack
    Pack no. 0:   Oracle VM VirtualBox Extension Pack
    Building IE 6 VM
    Checking for existing OVA at /home/user/.ievms/IE6 - WinXP.ova
    Downloading OVA ZIP from http://virtualization.modern.ie/vhd/IEKitV1_Final/VirtualBox/OSX/IE6_WinXP.zip to IE6_WinXP.zip (attempt 1 of 3)
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: virtualization.modern.ie
    \nERROR: Failed to download http://virtualization.modern.ie/vhd/IEKitV1_Final/VirtualBox/OSX/IE6_WinXP.zip to /home/user/.ievms/IE6_WinXP.zip using 'curl', error code (6)\n

**Comment by xdissent** [comment]
Hey sorry about that @chrisspen, some of the URLs have changed. I just pushed [an update](https://github.com/xdissent/ievms/commit/72e4b6d9d7913818ea193ffbf364692decc29618) that I'll release later today. You can try it now with: `curl -s https://raw.githubusercontent.com/xdissent/ievms/develop/ievms.sh | bash`

**Comment by xdissent** [comment]
Hey @chrisspen , 0.3.2 was just released. Please reopen if that doesn't work for you.

**Comment by chrisspen** [comment]
Thanks for the update. Although it gets further, it still fails, now with an VBoxManage error:

    $ curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | bash
    Checking for VirtualBox
    Checking for Oracle VM VirtualBox Extension Pack
    Pack no. 0:   Oracle VM VirtualBox Extension Pack
    Building IE 6 VM
    Checking for existing OVA at /home/chris/.ievms/IE6 - WinXP.ova
    Downloading OVA ZIP from https://az412801.vo.msecnd.net/vhd/IEKitV1_Final/VirtualBox/OSX/IE6_WinXP.zip to IE6_WinXP.zip (attempt 1 of 3)
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  716M  100  716M    0     0  1849k      0  0:06:36  0:06:36 --:--:-- 2911k
    MD5 check succeeded for IE6_WinXP.zip
    Extracting OVA from /home/chris/.ievms/IE6_WinXP.zip
    IE6_WinXP.zip: Zip
      IE6 - WinXP.ova  (759386624 B)... OK.
    Successfully extracted to "./IE6 - WinXP.ova".
    Checking for existing IE6 - WinXP VM
    Creating IE6 - WinXP VM (disk: /home/chris/.ievms/IE6 - WinXP-disk1.vmdk)
    0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
    Interpreting /home/chris/.ievms/IE6 - WinXP.ova...
    OK.
    Disks:
      vmdisk1	136260878336	-1	http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized	IE6 - WinXP-disk1.vmdk	-1	-1	

    Virtual system 0:
     0: Suggested OS type: "WindowsXP"
        (change with "--vsys 0 --ostype <type>"; use "list ostypes" to list all possible values)
     1: VM name specified with --vmname: "IE6 - WinXP"
     2: Number of CPUs: 2
        (change with "--vsys 0 --cpus <n>")
     3: Guest memory: 512 MB
        (change with "--vsys 0 --memory <MB>")
     4: Sound card (appliance expects "", can change on import)
        (disable with "--vsys 0 --unit 4 --ignore")
     5: USB controller
        (disable with "--vsys 0 --unit 5 --ignore")
     6: Network adapter: orig NAT, config 2, extra slot=0;type=NAT
     7: CD-ROM
        (disable with "--vsys 0 --unit 7 --ignore")
     8: IDE controller, type PIIX4
        (disable with "--vsys 0 --unit 8 --ignore")
     9: IDE controller, type PIIX4
        (disable with "--vsys 0 --unit 9 --ignore")
    10: Hard disk image: source image=IE6 - WinXP-disk1.vmdk, target path=/home/chris/.ievms/IE6 - WinXP-disk1.vmdk, controller=8;channel=0
    0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
    Successfully imported the appliance.
    Adding shared folder
    Building IE6 - WinXP VM
    build_ievm_ie6
    Downloading ievms control ISO from https://dl.dropboxusercontent.com/u/463624/ievms-control-0.3.2.iso to /home/chris/.ievms/ievms-control-0.3.2.iso (attempt 1 of 3)
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 3506k  100 3506k    0     0  3090k      0  0:00:01  0:00:01 --:--:-- 3088k
    MD5 check succeeded for /home/chris/.ievms/ievms-control-0.3.2.iso
    Attaching ievms control ISO
    Starting VM IE6 - WinXP
    Waiting for VM "IE6 - WinXP" to power on...
    VM "IE6 - WinXP" has been successfully started.
    Waiting for IE6 - WinXP to shutdown...
    Waiting for IE6 - WinXP to shutdown...
    Ejecting ievms control ISO
    Attaching Guest Additions
    VBoxManage: error: Cannot find the Guest Additions ISO image

**Comment by chrisspen** [comment]
Also, I don't appear to have permission to re-open the issue.

**Comment by xdissent** [comment]
Ah, some linux distros package the guest additions iso separately. Make sure you've got that installed too, like [this one](https://packages.debian.org/jessie/virtualbox-guest-additions-iso) for Debian. This should prob be in the README, sorry about that.

**Comment by chrisspen** [comment]
I'm on Ubuntu. I tried installing it with:

    sudo apt-get install virtualbox-guest-additions-iso

but re-running the script results in the same error.

Oddly, re-running it a second time succeeds.

**Comment by xdissent** [comment]
Hmm, the first time you ran it after installing guest additions, it likely thought the guest additions was already attached from the previous run, even though it was an invalid path. Then it ejected it, so the second time it attached correctly and worked. I think that explains it - make sense to you? Is everything working now that you have the correct ga iso?

**Comment by chrisspen** [comment]
Yeah, it looks good now. Thanks.
